### ISSUE TITLE
xml类型生成表提示功能不支持

### ISSUE THREAD

**Issue by 756616071** [donet5/WebFirst#11]
自定义添加了xml类型,但是生成表的时候提示不支持
![image](https://user-images.githubusercontent.com/44856671/170441774-6e6a990d-d3d8-41f1-bd1a-f315855e551b.png)

![RX7%58XEY2E}DF4OQ@_ XNR](https://user-images.githubusercontent.com/44856671/170441647-03603c33-a40d-44d7-ab87-f2fa86415743.png)

![TN3D{7Q9PSH1 ZNO4Q__SBM](https://user-images.githubusercontent.com/44856671/170441624-dc1cd11f-36d1-45b2-a70f-e7c38c8a5094.png)

**Comment by DotNetNext** [comment]
源码已修复
