### ISSUE TITLE
提个根据数据库表生成实体的建议

### ISSUE THREAD

**Issue by landonzeng** [donet5/WebFirst#18]
根据数据库表生成实体时能否直接读取数据库中表的类型、长度，根据数据库中表实际的类型和长度直接生成实体，现在有些类型如果数据类型里没有的话，需要配置类型才能生成，而且还需要定义类型长度，着实不方便，而且长度都并不是数据库中的长度

**Comment by DotNetNext** [comment]
后面加字段支持 原生字段作为模版字段

**Comment by landonzeng** [comment]
> 后面加字段支持 原生字段作为模版字段

大概什么时候能支持呢？

**Comment by DotNetNext** [comment]
已经支持了

**Comment by landonzeng** [comment]
> 已经支持了

好的，下载一下最新的试试看

**Comment by landonzeng** [comment]
> 已经支持了

下载了最新版本，使用的时候，mysql数据库里是text，dbfirst的时候还是生成了varchar(50),而且还有很多其他类型并没按mysql数据库中的类型和长度生成实体，是我哪里没用对么？
