### ISSUE TITLE
支持C# keyword转义

### ISSUE THREAD

**Issue by ghost** [donet5/WebFirst#2]
数据库里的Columns 有用到 ref 、static、void 、out 、var 等命名
期望能支持替换成 @/ref 、@/static、@/void 、@/out 、@/var
*
自己也可以手动处理,但这需要提供表名,列名才能重命名,无疑比较麻烦
希望有一个全局设置,支持自动转义.

**Comment by ghost** [comment]
提供一下手动处理方法

``Program.GenerationClass``

     db.DbMaintenance.GetTableInfoList().ForEach(table =>
     {
         db.MappingColumns.Add("@in", "in", table.Name);
         db.MappingColumns.Add("@out", "out", table.Name);
         db.MappingColumns.Add("@var", "var", table.Name);
         db.MappingColumns.Add("@ref", "ref", table.Name);
         db.MappingColumns.Add("@void", "void", table.Name);
         db.MappingColumns.Add("@static", "static", table.Name);
         db.MappingColumns.Add("@class", "class", table.Name);
         db.MappingColumns.Add("@operator", "operator", table.Name);
         db.MappingColumns.Add("@event", "event", table.Name);
         db.MappingColumns.Add("@virtual", "virtual", table.Name);
     });

**Comment by DotNetNext** [comment]
这个功能我会加到sqlsugar里面去，不需要你们在额外配置，你们先使用手动配置吧
