### ISSUE TITLE
最好把生成文件的部分都用模板，比如实体生成。

### ISSUE THREAD

**Issue by wang2650** [donet5/WebFirst#3]
最好把生成文件的部分都用模板，比如实体生成。
如果我要生成改实体类文件，还要去sqlsugar的DbFirstTemplate 中去改。
能全都改成DbContext.tt这样的模板就更好了。

**Comment by GuanBaozhou** [comment]
此版本在Mac 上跑不通 但是在windows上可以， 麻烦请验证下Mac是否不兼容 谢谢

**Comment by shelllee** [comment]
不用啊，自己扩展模板就可以，现在应该就缩进是定死的
