### ISSUE TITLE
小建议：增加定义配置项

### ISSUE THREAD

**Issue by staoran** [donet5/WebFirst#6]
希望能在配置 虚拟类 时，能够自定义一些选项，比如我可以通过自定义选项在 实体/表 的部分增加一个 是否多选或者是否自动生成单号，在 属性/字段 增加一个 控件类型 。然后在模版中就可以用到这些数据，生成出更完善的代码。特别是前端代码。

希望有一个字典配置模块，类似于现在的 数据类型 ，作为上述功能的数据源。

**Comment by DotNetNext** [comment]
好的需求收到

**Comment by DotNetNext** [comment]
已经支持该功能，后续文件会写出用法
