### ISSUE TITLE
数据库表导入数据生成类报错误

### ISSUE THREAD

**Issue by YellowTulipShow** [donet5/WebFirst#7]
![图片](https://user-images.githubusercontent.com/29710592/136652673-3b0ea7af-4ae9-449c-8a22-2d98ab124ee1.png)

![图片](https://user-images.githubusercontent.com/29710592/136652694-27554ec2-8488-41dd-b8bb-5f5aa3e35e76.png)

**Comment by DotNetNext** [comment]
是双击的时候报错是吗？

**Comment by DotNetNext** [comment]
可以重现双击会报错暂时不影响功能

**Comment by DotNetNext** [comment]
可以重现双击会报错暂时不影响功能

**Comment by YellowTulipShow** [comment]
双击单击都报错, 也没有触发导入的后续操作

**Comment by DotNetNext** [comment]
你这个不是chrome吧

**Comment by YellowTulipShow** [comment]
不是, 用的firefox

![图片](https://user-images.githubusercontent.com/29710592/136872713-9a56f92a-fc15-44af-882e-f34da113c87f.png)

**Comment by YellowTulipShow** [comment]
使用 chrome 依然报错

![图片](https://user-images.githubusercontent.com/29710592/136872978-de7f0388-6c4d-4a6b-9731-9df7fe4370bc.png)

![图片](https://user-images.githubusercontent.com/29710592/136873014-e1361ab6-2e73-4e2a-a572-e9ef6da35f90.png)
![图片](https://user-images.githubusercontent.com/29710592/136873024-78f8ee54-cbfd-468b-b44f-7207ff5465d2.png)

报: Uncaught ReferenceError: btnEdit is not defined

**Comment by DotNetNext** [comment]
获取最新的，修复过了

**Comment by DotNetNext** [comment]
还有问题吗？没问题我就关了

**Comment by YellowTulipShow** [comment]
没有了, 拉取最新版可以使用了, 辛苦
