### ISSUE TITLE
template format check plug

### ISSUE THREAD

**Issue by zouzjidelu** [donet5/WebFirst#8]
您好，我想问下，您的模板都是放在了 xxx.txt中，您在编写模板时，如何检测模板格式问题。使用的是什么插件？我想在您的这个基础上增加一些模板。

**Comment by DotNetNext** [comment]
菜单模版管理

**Comment by DotNetNext** [comment]
xxx.txt 只是初始化到数据库的，并不是TXT存的模版

**Comment by DotNetNext** [comment]
文档： https://www.donet5.com/Doc/11   模版管理 ，有可模版编辑器可以很好的写模版
